### PR TITLE
Add jitpack.yml for Java 17

### PR DESCRIPTION
**Pull request by CrimsonDawn45**
Adding a jitpack.yml file will allow this mod to build on Jitpack with Java 17 & people to make mods depending on this one using [Jitpack](https://jitpack.io/#kwpugh/gobber_fabric-1.17)

### CODE REVIEW

**Comment by kwpugh** [comment]
I'm still kind of learning all this stuff, what is the purpose of Jitpack?  What's the use case?

**Comment by CrimsonDawn45** [comment]
Jitpack is a website that lets anyone use any repository on Github as a dependency in their project.

**Comment by CrimsonDawn45** [comment]
And the jitpack.yml files I added tell jitpack the correct Java version to use. Because currently if I try and make a mod that depends on yours it tries to build your mod in Java 8 and fails.

**Comment by CrimsonDawn45** [comment]
Like without Jitpack, or you setting up a maven server for your mod. There isn't a way for me to even import your mod as a dependency.

**Comment by kwpugh** [comment]
the mod contains libs that I do not publish the source to, at this point.  what are you looking to do?

**Comment by CrimsonDawn45** [comment]
I was wanting to add integration with BasicShields and Gobber so that when both of our mods are installed it detects Gobber and adds shields for the Material Teirs

**Comment by kwpugh** [comment]
ahh, I figured that might be why.  you might want to look how https://www.curseforge.com/minecraft/mc-mods/harvest-scythes  did it.

**Comment by kwpugh** [comment]
seems like that mod is doing what you are looking to do.

**Comment by CrimsonDawn45** [comment]
It looks like they are using Jitpack as well but they are doing something different that lets them use it anyway hmm.

**Comment by CrimsonDawn45** [comment]
I was trying to add the jitpack.yml files because it makes it more convenient for anyone to make a mod that has integrations with yours.

**Comment by CrimsonDawn45** [comment]
Well, anyway if you want to add the jitpack.yml files you can I guess. Adding them would make it easier for people to make mods depend on yours. I was trying to add them because I didn't know it's even possible to do it with curseforge.

**Comment by kwpugh** [comment]
if you get it working, let me know.  I will add a link to the Gobber page to promote the mod.

**Comment by kwpugh** [comment]
BTW: I have been playing with some of your mods, very nice work.

**Comment by CrimsonDawn45** [comment]
Is there a better way to contact you besides talking on a GitHub issue? I got everything working already The only stuff I really need now is textures for everything, and trying to figure out how the gobber's special abilities will work with shields.

**Comment by kwpugh** [comment]
I have a Discord:  https://discord.gg/j7bYbkW

**Pull request closed without merging**
